repos:
  - repo: local
    hooks:
      - id: generate-api-client
        name: "Generate: API TypeScript types"
        entry: ./web/src/api/generate-api-pre-commit.sh
        language: system
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        name: "Validate: Commit is conventional"
        args:
          [
            build,
            chore,
            ci,
            ops,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
            _fix,
            _feat,
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        name: "Validate: parse .py files"
        language_version: python3.13
      - id: check-json
        name: "Validate: parse .json files"
        exclude: ".devcontainer"
      - id: check-yaml
        name: "Validate: parse .yaml files"
      - id: check-toml
        name: "Validate: parse .toml files"
      - id: check-merge-conflict
        name: "Validate: no merge conflict strings"
      - id: check-case-conflict
        name: "Validate: no case conflicting file names"
      - id: trailing-whitespace
        name: "Lint: remove trailing whitespaces"
        exclude: ^(.*\.(lock)$|docs/|web/src/api/generated/)
      - id: end-of-file-fixer
        name: "Lint: end all files with single empty line"
        exclude: ^(.*\.(lock)$|docs/|web/src/api/generated/)
      - id: mixed-line-ending
        exclude: ^(.*\.(lock)$|docs/|web/src/api/generated/)
      - id: detect-private-key
        exclude: api/tests/integration/conftest.py
        exclude_types:
          - markdown

  - repo: local
    hooks:
      - id: ruff
        name: "Lint: ruff (python)"
        language: system
        types: [text]
        files: "\\.py$"
        entry: mise run lint-ruff
        pass_filenames: false

  - repo: local
    hooks:
      - id: biome
        name: "Lint: biome (js/ts/json)"
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|s?css)$"
        entry: mise run lint-biome
        pass_filenames: false
