apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: mercury
  title: Mercury
  description: Mercury calculator
  annotations:
    github.com/project-slug: equinor/mercury
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://mercury.app.radix.equinor.com/
      title: Production app
      icon: star
    - url: https://proxy-mercury-dev.radix.equinor.com/
      title: Development app
      icon: unstarred
    - url: https://console.radix.equinor.com/applications/mercury
      title: Radix console
      icon: console
spec:
  type: product
  owner: team-hermes
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mercury-api
  title: Mercury API
  description: API for the Mercury calculator
  annotations:
    github.com/project-slug: equinor/mercury
    backstage.io/techdocs-entity: system:default/mercury
  links:
    - url: https://api-mercury-prod.radix.equinor.com/docs
      title: API documentation
      icon: api

spec:
  type: service
  owner: team-hermes
  lifecycle: production
  providesApis:
    - mercury-api
  dependsOn:
    - component:default/gpa-libhg
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mercury-auth-proxy
  title: Mercury Auth Proxy
  description: OAuth2 Proxy for authentication and authorization.
  tags:
    - oauth2
    - proxy
  annotations:
    github.com/project-slug: equinor/mercury
    backstage.io/techdocs-entity: system:default/mercury
spec:
  type: service
  lifecycle: production
  owner: team-hermes
  system: system:default/mercury
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mercury-frontend
  title: Mercury Frontend
  description: React frontend application for Mercury.
  tags:
    - frontend
    - react
    - typescript
  annotations:
    github.com/project-slug: equinor/mercury
    backstage.io/techdocs-entity: system:default/mercury
  links:
    - url: "https://mercury.app.radix.equinor.com/"
      title: "Mercury Application"
      icon: app
spec:
  type: website
  lifecycle: production
  owner: team-hermes
  system: system:default/mercury
  consumesApis:
    - mercury-api
  dependsOn:
    - component:default/mercury-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mercury-api
  title: Mercury API
  description: REST API for Mercury core analysis data.
  annotations:
    github.com/project-slug: equinor/mercury
    backstage.io/techdocs-entity: system:default/mercury
spec:
  type: openapi
  lifecycle: production
  owner: team-hermes
  system: system:default/mercury
  definition:
    $text: https://mercury.app.radix.equinor.com/api/openapi.json
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gpa-libhg
  title: GPA LibHg
  description: Hg / Mercury models, calculations.
  annotations:
    github.com/project-slug: equinor/gpa-libhg
    backstage.io/techdocs-entity: system:default/mercury
spec:
  type: library
  lifecycle: production
  owner: team-hermes
  system: system:default/mercury
