services:
  api:
    build:
      target: development
      cache_from:
        - ghcr.io/equinor/mercury-api:latest
    image: mercury-api-ci
    environment:
      ENVIRONMENT: local
      AUTH_ENABLED: false
