version: "3.8"

services:

  api:
    build:
      target: development
    image: api-dev
    volumes:
      - ./api/src/:/code
    env_file:
      - .env
    environment:
      ENVIRONMENT: local
      LOGGING_LEVEL: debug
      AUTH_ENABLED: 1
      OAUTH_TOKEN_ENDPOINT: $OAUTH_TOKEN_ENDPOINT
      OAUTH_AUTH_ENDPOINT: $OAUTH_AUTH_ENDPOINT
      OAUTH_WELL_KNOWN: $OAUTH_WELL_KNOWN
      OAUTH_AUDIENCE: $OAUTH_AUDIENCE
      APPINSIGHTS_CONSTRING: $APPINSIGHTS_CONSTRING
    ports:
      - "5000:5000"

  web:
    build:
      target: development
      args:
        AUTH_ENABLED: 1
        AUTH_SCOPE: $AUTH_SCOPE
        CLIENT_ID: $CLIENT_ID
        TENANT_ID: $TENANT_ID
        REDIRECT_URI: http://localhost/
        APP_INSIGHT_CON_STRING: $APPINSIGHTS_CONSTRING
    image: web-dev
    stdin_open: true
    volumes:
      - ./web/src:/code/src
      - ./web/node_modules:/code/src/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development