site_name: Mercury Documentation
site_url: https://mercury.app.radix.equinor.com/docs
site_description: Documentation for Mercury calculator
site_author: Team Hermes
repo_url: https://github.com/equinor/mercury
docs_dir: docs
theme:
  name: material
plugins:
  - techdocs-core
nav:
  - Welcome to Mercury: index.md
  - Mercury developers:
      - Overview: developers/guide/index.md
      - Setup: developers/guide/setup.md
      - Running: developers/guide/running.md
      - Testing: developers/guide/testing.md
      - Upgrading: developers/guide/upgrading.md
      - How We Work: developers/guide/how-we-work.md
  - Contributing Guide: contributing.md
  - Runbook: runbook.md
