[info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''

[generate-api-types]
description = "Generate API types for typescript"
dir = "{{ config_root }}/web"
run = "yarn generate"
