# security headers
add_header X-Content-Type-Options       "nosniff" always;
add_header Referrer-Policy              "no-referrer-when-downgrade" always;
add_header Content-Security-Policy      "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://cdn.eds.equinor.com; font-src 'self' https://cdn.eds.equinor.com; img-src 'self' data:; connect-src 'self' https://login.microsoftonline.com; frame-ancestors 'self';" always;
add_header Permissions-Policy           "camera=(), microphone=(), geolocation=(), payment=()" always;
add_header Strict-Transport-Security    "max-age=31536000; includeSubDomains; preload" always;
