name: "Linting and checks"
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Linting and checks: ${{ matrix.title }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: "Pre-commit with prek"
            task: lint-pre-commit
          - title: "mypy type check"
            task: lint-mypy
          - title: "Typescript compilation"
            task: lint-typescript-compilation
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4

      - name: "Run: ${{ matrix.title }}"
        run: mise run ${{ matrix.task }}
