name: "Linting and checks"
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    name: "Linting and checks: Pre-commit"
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@v3

      - name: "Run: Pre-commit with prek"
        run: mise run lint-pre-commit

  mypy:
    runs-on: ubuntu-latest
    name: "mypy static type checking"
    steps:
      - name: "Setup: check out repository"
        uses: actions/checkout@v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@v3

      - name: "Run: mypy type check"
        run: mise run lint-mypy

  typescript-compile:
    runs-on: ubuntu-latest
    name: "typescript compilation"
    steps:
      - name: "Setup: check out repository"
        uses: actions/checkout@v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@v3

      - name: "Run: typescript compilation"
        run: mise run lint-typescript-compilation
