name: "On tag: release main to prod"
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      LIBHG_REPO_DEPLOY_KEY: ${{ secrets.LIBHG_REPO_DEPLOY_KEY }}

  set-tag-ref:
    runs-on: ubuntu-latest
    outputs:
      tag-ref: ${{ steps.get-tag-ref.outputs.tag-ref }}
    steps:
      - uses: actions/checkout@master
      - id: get-tag-ref
        run: |
          TAG_REF=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "tag-ref=$TAG_REF" >> $GITHUB_OUTPUT

  publish-image:
    needs: [set-tag-ref, tests]
    uses: ./.github/workflows/publish.yaml
    with:
      image-tags: production,${{ needs.set-tag-ref.outputs.tag-ref }}
      oauth-redirect-url: https://mercury.app.radix.equinor.com
    secrets:
      LIBHG_REPO_DEPLOY_KEY: ${{ secrets.LIBHG_REPO_DEPLOY_KEY }}
      APP_INSIGHT_CON_STRING: ${{ secrets.APP_INSIGHT_CON_STRING_PROD }}

  deploy:
    needs: publish-image
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: "prod"
