name: "Tests"
on:
  workflow_call:
    secrets:
      LIBHG_PAT:
        description: "PAT for accessing libhg repository"
        required: true

permissions:
  contents: read
  packages: read

env:
  API_IMAGE: ghcr.io/equinor/mercury-api

jobs:
  test-api:
    runs-on: ubuntu-latest
    name: "Tests: API"
    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@v4

      - name: "Setup: Login to image registry"
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup: set up Docker Buildx"
        uses: docker/setup-buildx-action@v4

      - name: "Setup: Build API test image"
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./api
          target: development
          load: true
          tags: mercury-api-ci
          cache-from: type=registry,ref=${{ env.API_IMAGE }}:latest
          build-args: |
            LIBHG_VERSION=${{ vars.LIBHG_VERSION }}
          secrets: |
            libhg-pat=${{ secrets.LIBHG_PAT }}

      - name: "Run: Unit tests with python"
        run: mise run docker-pytest-ci -m unit

      - name: "Run: Integration tests with python"
        run: mise run docker-pytest-ci -m integration

  test-web:
    runs-on: ubuntu-latest
    name: "Tests: Web"
    steps:
      - name: "Setup: check out repository"
        uses: actions/checkout@v6

      - name: "Setup: install mise"
        uses: jdx/mise-action@v4

      - name: "Run: Tests with yarn"
        run: mise run test-web-unit
